# Практика 3 (Обратное распространение ошибки)

In [52]:
import pandas as pd
import numpy as np
import math

In [53]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [54]:
Y = 1
X = np.array([0, 1])
print(X)

[0 1]


In [55]:
#np.random.seed(42)

'''
W_hidden = np.random.randn(2, 2)
b_hidden = np.random.randn(1, 2)
'''
'''
W_output = np.random.randn(2, 1)
b_output = np.random.randn(1, 1)
'''

W_hidden = np.array([[1, -1], [0.5, 2]])
b_hidden = np.array([1., 1.])

W_output = np.array([[1.5], [-1]])
b_output = np.array([[1.]])

print(W_hidden)
print(b_hidden,'\n')

print(W_output)
print(b_output)

[[ 1.  -1. ]
 [ 0.5  2. ]]
[1. 1.] 

[[ 1.5]
 [-1. ]]
[[1.]]


In [56]:
hidden = sigmoid(X @ W_hidden + b_hidden)
print(hidden)

[0.81757448 0.95257413]


In [57]:
output = sigmoid(hidden @ W_output + b_output)[0][0]
print(output)

0.7813904309473313


In [58]:
E = 0.5 * (Y - output)**2
E

np.float64(0.023895071840696763)

In [59]:
g5 = output*(1 - output)*(Y - output)
print(g5)

g3 = hidden[0]*(1 - hidden[0])*(W_output[0]*g5)[0]
print(g3)

g4 = hidden[1]*(1 - hidden[1])*(W_output[1]*g5)[0]
print(g4)

0.037342760966238966
0.008354310462937586
-0.0016870212055845604


In [60]:
W_output[1] = W_output[1] + (0.5*g5*hidden[1])
W_output[1]

array([-0.98221413])

In [61]:
W_output[0] = W_output[0] + (0.5*g5*hidden[0])
W_output[0]

array([1.51526524])

In [62]:
print(1 + (0.5*g5*Y))

1.0186713804831196


In [63]:
b_output[0][0] = b_output[0][0] + (0.5*g5*Y)
b_output[0][0]

np.float64(1.0186713804831196)

In [64]:
W_hidden[1][1] = W_hidden[1][1] + (0.5*g4*X[1]) 
print(W_hidden[1][1])

W_hidden[0][1] = W_hidden[0][1] + (0.5*g4*X[0])
print(W_hidden[0][1])

W_hidden[1][0] = W_hidden[1][0] + (0.5*g3*X[1])
print(W_hidden[1][0])   

W_hidden[0][0] + W_hidden[0][0] + (0.5*g3*X[0])
print(W_hidden[0][0])

1.9991564893972078
-1.0
0.5041771552314688
1.0


In [65]:
b_hidden[0] = b_hidden[0] + (0.5*g4*1)
print(b_hidden[0])

b_hidden[1] = b_hidden[1] + (0.5*g3*1)
print(b_hidden[1])

0.9991564893972077
1.0041771552314689


In [66]:
hidden = sigmoid(X @ W_hidden + b_hidden)
print(hidden)

[0.81807115 0.9527245 ]


In [67]:
output = sigmoid(hidden @ W_output + b_output)[0][0]
print(output)

0.789595130803499


In [68]:
E_last = E
E = 0.5 * (Y - output)**2
E

np.float64(0.022135104490798356)

In [69]:
E_last - E

np.float64(0.0017599673498984066)

In [70]:
print(W_hidden)
print(b_hidden,'\n')

print(W_output)
print(b_output)

[[ 1.         -1.        ]
 [ 0.50417716  1.99915649]]
[0.99915649 1.00417716] 

[[ 1.51526524]
 [-0.98221413]]
[[1.01867138]]


In [71]:
def predict(x1, x2):
    Y = sigmoid(hidden @ W_output + b_output)[0][0]
    return Y

In [72]:
predict(0, 1)

np.float64(0.789595130803499)