# Практика 4 (радиально-базисные нейронные сети)

In [438]:
import torch
import math

In [439]:
X = torch.tensor([0.9, 2.1, 3.1])   
Y = torch.tensor([1.0, 1.9, 3.0])

In [440]:
'''
X = torch.tensor([])
Y = torch.tensor([])
for i in range(200):
    X = torch.cat([X, torch.tensor([i])])
    Y = torch.cat([Y, torch.tensor([i*2])])

print(X.shape)
print(Y.shape)'''

'\nX = torch.tensor([])\nY = torch.tensor([])\nfor i in range(200):\n    X = torch.cat([X, torch.tensor([i])])\n    Y = torch.cat([Y, torch.tensor([i*2])])\n\nprint(X.shape)\nprint(Y.shape)'

In [441]:
print(X)
print(Y)

tensor([0.9000, 2.1000, 3.1000])
tensor([1.0000, 1.9000, 3.0000])


In [442]:
#выходы радиально-базисных нейронов
def h_i(x, c):
    return math.exp(-(x - c)**2)


In [443]:
def radial_basis_nn(x, y):
    #Рассчёт центров функции активации:
    C_i = torch.tensor([])
    for i in range(x.shape[0] - 1):
        C_i = torch.cat([C_i, torch.tensor([(x[i] + x[i+1])/2])])
    print(f"Центры функции активации: {C_i}", "\n")


    #ребуется найти неизвестные коэффициенты 𝑤i:
    F = torch.zeros(x.shape[0], x.shape[0] - 1)
    for i in range(F.shape[0]):
        for j in range(F[i].shape[0]):
            F[i][j] = h_i(x[i], C_i[j])
    print("Матрица F, элементов h_i(x_i):")
    print(F, "\n")


    print("Транспонированная матрица F:")
    F_T = F.T
    print(F_T, "\n")

    print("Умнажаем строку на столбец:")
    F_FT = F_T @ F
    print(F_FT)

    print("Обратная матрица:")
    FFT_inv = torch.linalg.inv(F_FT)
    print(FFT_inv, "\n")

    print("Ответ:")
    W = (FFT_inv @ F_T) @ y.T
    print(W)
    return(W, C_i)

In [444]:
W, C = radial_basis_nn(X, Y)

Центры функции активации: tensor([1.5000, 2.6000]) 

Матрица F, элементов h_i(x_i):
tensor([[0.6977, 0.0556],
        [0.6977, 0.7788],
        [0.0773, 0.7788]]) 

Транспонированная матрица F:
tensor([[0.6977, 0.6977, 0.0773],
        [0.0556, 0.7788, 0.7788]]) 

Умнажаем строку на столбец:
tensor([[0.9795, 0.6423],
        [0.6423, 1.2162]])
Обратная матрица:
tensor([[ 1.5620, -0.8250],
        [-0.8250,  1.2580]]) 

Ответ:
tensor([0.3284, 3.0101])


In [445]:
def predict(X, W, C):
    F = torch.zeros(X.shape[0], C.shape[0])
    for i in range(X.shape[0]):
        for j in range(C.shape[0]):
            F[i][j] = h_i(X[i], C[j])
    print("Матрица признаков для предсказания:")
    print(F, "\n")

    y_pred = F @ W
    print("Предсказанные значения:")
    print(y_pred)

In [446]:
predict(X, W, C)    

Матрица признаков для предсказания:
tensor([[0.6977, 0.0556],
        [0.6977, 0.7788],
        [0.0773, 0.7788]]) 

Предсказанные значения:
tensor([0.3964, 2.5734, 2.3697])
